// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAykJ9Unr0rADDHP6GGy_hvTyEDZJNVQgs',
    appId: '1:124684460884:web:5fdd32379111522b7e1ec1',
    messagingSenderId: '124684460884',
    projectId: 'roboti-57979',
    authDomain: 'roboti-57979.firebaseapp.com',
    storageBucket: 'roboti-57979.appspot.com',
    measurementId: 'G-KSYQ4GQKT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTeTRtUsXN-2kmijDUOO0thUdPkoy7pKc',
    appId: '1:124684460884:android:b8f4d5b9354f96907e1ec1',
    messagingSenderId: '124684460884',
    projectId: 'roboti-57979',
    storageBucket: 'roboti-57979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArLAm6g2mm7R-twKIytUQRobDcmiSXXXo',
    appId: '1:124684460884:ios:61d646511f0ae6107e1ec1',
    messagingSenderId: '124684460884',
    projectId: 'roboti-57979',
    storageBucket: 'roboti-57979.appspot.com',
    androidClientId: '124684460884-0hlgevcji4hdf0csgp80bbu0n0r35o1j.apps.googleusercontent.com',
    iosClientId: '124684460884-5csvahfa1oubaa384kkshrps22ivh3a6.apps.googleusercontent.com',
    iosBundleId: 'com.app.roboti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArLAm6g2mm7R-twKIytUQRobDcmiSXXXo',
    appId: '1:124684460884:ios:721ac2fcb05b8d597e1ec1',
    messagingSenderId: '124684460884',
    projectId: 'roboti-57979',
    storageBucket: 'roboti-57979.appspot.com',
    androidClientId: '124684460884-0hlgevcji4hdf0csgp80bbu0n0r35o1j.apps.googleusercontent.com',
    iosClientId: '124684460884-qbfo38kk42qu0cv84legd56h2qlf6saa.apps.googleusercontent.com',
    iosBundleId: 'com.example.robotiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAykJ9Unr0rADDHP6GGy_hvTyEDZJNVQgs',
    appId: '1:124684460884:web:8b2f12699b93ed527e1ec1',
    messagingSenderId: '124684460884',
    projectId: 'roboti-57979',
    authDomain: 'roboti-57979.firebaseapp.com',
    storageBucket: 'roboti-57979.appspot.com',
    measurementId: 'G-5K8J1C8HRN',
  );
}
